using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace KObjectMapper.SourceGenerator;

[Generator]
public sealed class MappingPlanGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(INamedTypeSymbol Source, INamedTypeSymbol Target, Location Location)> pairs =
            context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (node, _) => node is InvocationExpressionSyntax,
                    transform: static (ctx, _) => TryGetMappingPair(ctx))
                .Where(static p => p.HasValue)
                .Select(static (p, _) => p!.Value);

        context.RegisterSourceOutput(
            pairs.Combine(context.CompilationProvider),
            static (ctx, pair) => Execute(ctx, pair.Left.Source, pair.Left.Target, pair.Left.Location));
    }

    private static (INamedTypeSymbol Source, INamedTypeSymbol Target, Location Location)? TryGetMappingPair(
        GeneratorSyntaxContext context)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
            return null;

        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol method)
            return null;

        if (method.Name != "CreateMap" || method.TypeArguments.Length != 2)
            return null;

        if (method.TypeArguments[0] is not INamedTypeSymbol source ||
            method.TypeArguments[1] is not INamedTypeSymbol target)
            return null;

        return (source, target, invocation.GetLocation());
    }

    private static void Execute(
        SourceProductionContext context,
        INamedTypeSymbol sourceType,
        INamedTypeSymbol targetType,
        Location location)
    {
        IReadOnlyList<IPropertySymbol> sourceProps = GetPublicProperties(sourceType);
        IReadOnlyList<IPropertySymbol> targetProps = GetPublicProperties(targetType);

        List<MappableProperty> mappable = new();

        foreach (IPropertySymbol sourceProp in sourceProps)
        {
            IPropertySymbol? targetProp = targetProps.FirstOrDefault(p => p.Name == sourceProp.Name);

            if (targetProp is null)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MappingDiagnostics.MissingTargetProperty,
                    Location.None,
                    sourceProp.Name,
                    sourceType.Name,
                    targetType.Name));
                continue;
            }

            if (!IsAssignable(sourceProp.Type, targetProp.Type))
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    MappingDiagnostics.TypeMismatch,
                    Location.None,
                    sourceProp.Name,
                    sourceProp.Type.Name,
                    targetProp.Type.Name));
                continue;
            }

            mappable.Add(new MappableProperty(sourceProp.Name, sourceProp.Type.ToDisplayString()));
        }

        string source = GenerateMapper(sourceType, targetType, mappable);
        string hintName = $"{sourceType.Name}To{targetType.Name}Mapper.g.cs";
        context.AddSource(hintName, SourceText.From(source, Encoding.UTF8));
    }

    private static IReadOnlyList<IPropertySymbol> GetPublicProperties(INamedTypeSymbol type)
    {
        List<IPropertySymbol> result = new();
        INamedTypeSymbol? current = type;
        while (current is not null)
        {
            foreach (ISymbol member in current.GetMembers())
            {
                if (member is IPropertySymbol prop &&
                    prop.DeclaredAccessibility == Accessibility.Public &&
                    !prop.IsStatic &&
                    !prop.IsIndexer)
                {
                    result.Add(prop);
                }
            }
            current = current.BaseType;
        }
        return result;
    }

    private static bool IsAssignable(ITypeSymbol source, ITypeSymbol target)
    {
        return SymbolEqualityComparer.Default.Equals(source, target) ||
               source.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, target));
    }

    private static string GenerateMapper(
        INamedTypeSymbol sourceType,
        INamedTypeSymbol targetType,
        IReadOnlyList<MappableProperty> properties)
    {
        string sourceFullName = sourceType.ToDisplayString();
        string targetFullName = targetType.ToDisplayString();

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("namespace KObjectMapper.Generated;");
        sb.AppendLine();
        sb.AppendLine($"public static class {sourceType.Name}To{targetType.Name}Mapper");
        sb.AppendLine("{");
        sb.AppendLine($"    public static void Map({sourceFullName} source, {targetFullName} target)");
        sb.AppendLine("    {");
        foreach (MappableProperty prop in properties)
        {
            sb.AppendLine($"        target.{prop.Name} = source.{prop.Name};");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
