using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace KObjectMapper.SourceGenerator.Tests;

/// <summary>
/// TDD tests for MappingPlanGenerator (US-07).
/// Verifies that the incremental source generator produces correct compile-time
/// mapping implementations for registered source/target pairs.
/// </summary>
public class MappingPlanGeneratorTests
{
    // ── US-07 AC1: Incremental source generator produces mapping implementations ──

    [Fact]
    public async Task Generator_ProducesMapperClass_ForSimpleTypePair()
    {
        string source = """
            using KObjectMapper.Configuration;

            namespace MyApp;

            public class Source { public string Name { get; set; } = ""; public int Age { get; set; } }
            public class Target { public string Name { get; set; } = ""; public int Age { get; set; } }

            public class MyProfile : MappingProfile
            {
                protected override void Configure()
                {
                    CreateMap<Source, Target>();
                }
            }
            """;

        string expectedGenerated = """
            // <auto-generated/>
            // Generated by KObjectMapper.SourceGenerator — do not edit manually.

            namespace KObjectMapper.Generated;

            /// <summary>
            /// Compile-time generated mapper from <see cref="MyApp.Source"/> to <see cref="MyApp.Target"/>.
            /// </summary>
            public static class SourceToTargetMapper
            {
                /// <summary>Maps all compatible properties from <paramref name="source"/> into <paramref name="target"/>.</summary>
                public static void Map(MyApp.Source source, MyApp.Target target)
                {
                    if (source is null) throw new System.ArgumentNullException(nameof(source));
                    if (target is null) throw new System.ArgumentNullException(nameof(target));

                    target.Name = source.Name;
                    target.Age = source.Age;
                }

                /// <summary>Creates a new <see cref="MyApp.Target"/> and maps all compatible properties from <paramref name="source"/>.</summary>
                public static MyApp.Target Map(MyApp.Source source)
                {
                    MyApp.Target target = new();
                    Map(source, target);
                    return target;
                }
            }

            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);
        test.TestState.GeneratedSources.Add(
            ($"{typeof(MappingPlanGenerator).Assembly.GetName().Name}\\KObjectMapper.SourceGenerator.MappingPlanGenerator\\SourceToTargetMapper.g.cs",
             SourceText.From(expectedGenerated, Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_ProducesNoOutput_WhenNoMappingProfileSubclassPresent()
    {
        string source = """
            namespace MyApp;
            public class Source { public string Name { get; set; } = ""; }
            public class Target { public string Name { get; set; } = ""; }
            public class NotAProfile { }
            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);
        // No generated sources expected
        await test.RunAsync();
    }

    // ── US-07 AC2: Generated mappers compile without consumer-written partial methods ──

    [Fact]
    public async Task Generator_ProducesStaticClass_WithNoPartialMethodRequirement()
    {
        string source = """
            using KObjectMapper.Configuration;

            namespace MyApp;

            public class OrderSource { public string OrderId { get; set; } = ""; public decimal Total { get; set; } }
            public class OrderTarget { public string OrderId { get; set; } = ""; public decimal Total { get; set; } }

            public class OrderProfile : MappingProfile
            {
                protected override void Configure()
                {
                    CreateMap<OrderSource, OrderTarget>();
                }
            }
            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);
        test.TestState.GeneratedSources.Add(
            ($"{typeof(MappingPlanGenerator).Assembly.GetName().Name}\\KObjectMapper.SourceGenerator.MappingPlanGenerator\\OrderSourceToOrderTargetMapper.g.cs",
             SourceText.From(GetExpectedOrderMapper(), Encoding.UTF8)));

        await test.RunAsync();
    }

    // ── US-07 AC3: Build diagnostics identify unsupported member patterns ──

    [Fact]
    public async Task Generator_EmitsKOM001Warning_WhenSourcePropertyHasNoMatchOnTarget()
    {
        string source = """
            using KObjectMapper.Configuration;

            namespace MyApp;

            public class Source { public string Name { get; set; } = ""; public string ExtraField { get; set; } = ""; }
            public class Target { public string Name { get; set; } = ""; }

            public class MyProfile : MappingProfile
            {
                protected override void Configure()
                {
                    CreateMap<Source, Target>();
                }
            }
            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);

        // Expect KOM001 warning for ExtraField not found on Target
        test.TestState.ExpectedDiagnostics.Add(
            new DiagnosticResult("KOM001", DiagnosticSeverity.Warning)
                .WithMessage("Source property 'Source.ExtraField' has no matching writable property on 'Target'."));

        test.TestState.GeneratedSources.Add(
            ($"{typeof(MappingPlanGenerator).Assembly.GetName().Name}\\KObjectMapper.SourceGenerator.MappingPlanGenerator\\SourceToTargetMapper.g.cs",
             SourceText.From(GetExpectedNameOnlyMapper(), Encoding.UTF8)));

        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_EmitsKOM001Warning_WhenTypeMismatchPreventsDirectAssignment()
    {
        string source = """
            using KObjectMapper.Configuration;

            namespace MyApp;

            public class Source { public string Count { get; set; } = ""; }
            public class Target { public int Count { get; set; } }

            public class MyProfile : MappingProfile
            {
                protected override void Configure()
                {
                    CreateMap<Source, Target>();
                }
            }
            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);

        // Expect KOM001 warning for type mismatch (string vs int)
        test.TestState.ExpectedDiagnostics.Add(
            new DiagnosticResult("KOM001", DiagnosticSeverity.Warning)
                .WithMessage("Type mismatch: 'Source.Count' (string) cannot be directly assigned to 'Target.Count' (int). A type converter may be required."));

        // No generated source because no mappable properties remain
        await test.RunAsync();
    }

    [Fact]
    public async Task Generator_ProducesMultipleMappers_ForMultipleCreateMapCalls()
    {
        string source = """
            using KObjectMapper.Configuration;

            namespace MyApp;

            public class A { public string X { get; set; } = ""; }
            public class B { public string X { get; set; } = ""; }
            public class C { public string X { get; set; } = ""; }
            public class D { public string X { get; set; } = ""; }

            public class MultiProfile : MappingProfile
            {
                protected override void Configure()
                {
                    CreateMap<A, B>();
                    CreateMap<C, D>();
                }
            }
            """;

        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = BuildTest(source);
        test.TestState.GeneratedSources.Add(
            ($"{typeof(MappingPlanGenerator).Assembly.GetName().Name}\\KObjectMapper.SourceGenerator.MappingPlanGenerator\\AToBMapper.g.cs",
             SourceText.From(GetExpectedXMapper("MyApp.A", "MyApp.B", "AToBMapper"), Encoding.UTF8)));
        test.TestState.GeneratedSources.Add(
            ($"{typeof(MappingPlanGenerator).Assembly.GetName().Name}\\KObjectMapper.SourceGenerator.MappingPlanGenerator\\CToDMapper.g.cs",
             SourceText.From(GetExpectedXMapper("MyApp.C", "MyApp.D", "CToDMapper"), Encoding.UTF8)));

        await test.RunAsync();
    }

    // ── Helpers ──────────────────────────────────────────────────────────────────

    private static CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> BuildTest(string source)
    {
        CSharpSourceGeneratorTest<MappingPlanGenerator, DefaultVerifier> test = new()
        {
            TestState =
            {
                Sources =
                {
                    // Provide a stub MappingProfile so the semantic model resolves the base class
                    ("MappingProfileStub.cs", MappingProfileStub),
                    ("TestSource.cs", source)
                }
            }
        };
        return test;
    }

    private const string MappingProfileStub = """
        namespace KObjectMapper.Configuration;

        public abstract class MappingProfile
        {
            protected MappingProfile() { Configure(); }
            protected abstract void Configure();
            protected object CreateMap<TSource, TTarget>() => null!;
        }
        """;

    private static string GetExpectedOrderMapper() => """
        // <auto-generated/>
        // Generated by KObjectMapper.SourceGenerator — do not edit manually.

        namespace KObjectMapper.Generated;

        /// <summary>
        /// Compile-time generated mapper from <see cref="MyApp.OrderSource"/> to <see cref="MyApp.OrderTarget"/>.
        /// </summary>
        public static class OrderSourceToOrderTargetMapper
        {
            /// <summary>Maps all compatible properties from <paramref name="source"/> into <paramref name="target"/>.</summary>
            public static void Map(MyApp.OrderSource source, MyApp.OrderTarget target)
            {
                if (source is null) throw new System.ArgumentNullException(nameof(source));
                if (target is null) throw new System.ArgumentNullException(nameof(target));

                target.OrderId = source.OrderId;
                target.Total = source.Total;
            }

            /// <summary>Creates a new <see cref="MyApp.OrderTarget"/> and maps all compatible properties from <paramref name="source"/>.</summary>
            public static MyApp.OrderTarget Map(MyApp.OrderSource source)
            {
                MyApp.OrderTarget target = new();
                Map(source, target);
                return target;
            }
        }

        """;

    private static string GetExpectedNameOnlyMapper() => """
        // <auto-generated/>
        // Generated by KObjectMapper.SourceGenerator — do not edit manually.

        namespace KObjectMapper.Generated;

        /// <summary>
        /// Compile-time generated mapper from <see cref="MyApp.Source"/> to <see cref="MyApp.Target"/>.
        /// </summary>
        public static class SourceToTargetMapper
        {
            /// <summary>Maps all compatible properties from <paramref name="source"/> into <paramref name="target"/>.</summary>
            public static void Map(MyApp.Source source, MyApp.Target target)
            {
                if (source is null) throw new System.ArgumentNullException(nameof(source));
                if (target is null) throw new System.ArgumentNullException(nameof(target));

                target.Name = source.Name;
            }

            /// <summary>Creates a new <see cref="MyApp.Target"/> and maps all compatible properties from <paramref name="source"/>.</summary>
            public static MyApp.Target Map(MyApp.Source source)
            {
                MyApp.Target target = new();
                Map(source, target);
                return target;
            }
        }

        """;

    private static string GetExpectedXMapper(string sourceType, string targetType, string className) =>
        $$"""
        // <auto-generated/>
        // Generated by KObjectMapper.SourceGenerator — do not edit manually.

        namespace KObjectMapper.Generated;

        /// <summary>
        /// Compile-time generated mapper from <see cref="{{sourceType}}"/> to <see cref="{{targetType}}"/>.
        /// </summary>
        public static class {{className}}
        {
            /// <summary>Maps all compatible properties from <paramref name="source"/> into <paramref name="target"/>.</summary>
            public static void Map({{sourceType}} source, {{targetType}} target)
            {
                if (source is null) throw new System.ArgumentNullException(nameof(source));
                if (target is null) throw new System.ArgumentNullException(nameof(target));

                target.X = source.X;
            }

            /// <summary>Creates a new <see cref="{{targetType}}"/> and maps all compatible properties from <paramref name="source"/>.</summary>
            public static {{targetType}} Map({{sourceType}} source)
            {
                {{targetType}} target = new();
                Map(source, target);
                return target;
            }
        }

        """;
}
