name: Dotnet Core CI

on:
  push:
    branches:
      - "main"

jobs:
  dotnet-core-ci:
    name: Executing Dotnet Core CI steps ...
    runs-on: ubuntu-latest

    steps:
      - name: Checking out source code from repo ...
        uses: actions/checkout@v3

      - name: Setting up the .NET Core SDK ...
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restoring Nuget packages ...
        run: dotnet restore

      - name: Building ...
        run: dotnet build -c Release --no-restore

      - name: Testing ...
        run: dotnet test --no-restore --verbosity normal
