<<<<<<<<< Temporary merge branch 1:.github/workflows/dotnet-ci.yml
name: Dotnet Core CI

on:
  push:
    branches:
      - "main"

jobs:
  dotnet-core-ci:
    name: Executing Dotnet Core CI steps ...
    runs-on: ubuntu-latest
=========
name: Dotnet CI Build

on:
  push:
    branches: ["main","dev"]
  pull_request:
    branches: ["main","dev"]

jobs:
  deploy:
    name: CI - Restore, build, test ...
    runs-on: ubuntu-latest   
>>>>>>>>> Temporary merge branch 2:.github/workflows/dotnet-ci-wf.yml

    steps:
      - name: Checking out source code from repo ...
        uses: actions/checkout@v3

      - name: Setting up the .NET Core SDK ...
        uses: actions/setup-dotnet@v3
        with:
<<<<<<<<< Temporary merge branch 1:.github/workflows/dotnet-ci.yml
          dotnet-version: 6.0.x
=========
          dotnet-version: 6.0.x      
>>>>>>>>> Temporary merge branch 2:.github/workflows/dotnet-ci-wf.yml

      - name: Restoring Nuget packages ...
        run: dotnet restore

<<<<<<<<< Temporary merge branch 1:.github/workflows/dotnet-ci.yml
      - name: Building ...
        run: dotnet build -c Release --no-restore
=========
      - name: Building the Libraries.sln solution ,,,
        run: dotnet build ObjectMapper.sln -c Release
>>>>>>>>> Temporary merge branch 2:.github/workflows/dotnet-ci-wf.yml

      - name: Testing ...
        run: dotnet test --no-restore --verbosity normal
